### ISSUE TITLE
Whitespace is not allowed in the sequence

### ISSUE THREAD

**Issue by m-noonan** [shimlab/BLAZE#10]
Hello,

I ran BLAZE with one scLR sample and got this error. I ran the test data and it ran perfectly fine. Is it something to do with my fastq file?

Command:
python3 blaze.py --expect-cells=200 --threads=12 /home/data/mnoonan/blaze_test/ERR9958136.fastq.gz

Getting putative barcodes from 1 FASTQ files...
Processed: 4956000Read [28:09, 3104.09Read/s]Traceback (most recent call last):
  File "/home/users/mnoonan/BLAZE/bin/blaze.py", line 528, in <module>
    main()
  File "/home/users/mnoonan/BLAZE/bin/blaze.py", line 476, in main
    for idx, f in enumerate(rst_futures):
  File "/home/users/mnoonan/BLAZE/bin/helper.py", line 114, in multiprocessing_submit
    i = next(iterator, None)
  File "/home/users/mnoonan/BLAZE/bin/blaze.py", line 440, in read_batch_generator
    for batch in read_batch:
  File "/home/users/mnoonan/BLAZE/bin/helper.py", line 165, in batch_iterator
    for entry in iterator:
  File "/home/data/mnoonan/anaconda3/envs/blaze/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 73, in __next__
    return next(self.records)
  File "/home/data/mnoonan/anaconda3/envs/blaze/lib/python3.7/site-packages/Bio/SeqIO/QualityIO.py", line 1080, in iterate
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/home/data/mnoonan/anaconda3/envs/blaze/lib/python3.7/site-packages/Bio/SeqIO/QualityIO.py", line 949, in FastqGeneralIterator
    raise ValueError("Whitespace is not allowed in the sequence.")
ValueError: Whitespace is not allowed in the sequence.
Processed: 4956000Read [28:16, 2920.75Read/s]

**Comment by m-noonan** [comment]
I tried it with the promethION_LSK110 fastq file used in your paper and it worked, so maybe something was wrong with the other file, which was the scimixology2 fastq.

**Comment by m-noonan** [comment]
I tried it with the promethION_LSK110 fastq file used in your paper and it worked, so maybe something was wrong with the other file, which was the scmixology2 fastq.
